In [3]:
import numpy as np 

In [4]:

#LU decomposition 

A = np.matrix([[2,4,5,-3],[10,19,27,-14],[6,16,11,-11],[-4,-11,4,19]])
def lu(A):
  
    n= A.shape[0]
    U = A
    L = np.array([[1 if i == j else 0 for j in range(n)] for i in range(n)])
    for j in range(0,n-1):
        for i in range(j+1,n):
            m = A[i,j]/A[j,j]
            U[i,j+1:n]= U[i, j+1:n] - m * U[j,j+1:n]
            L[i,j] = m
            U[i,j] = 0
    return L ,U 




L ,U = lu(A)
print('L=\n',L)
print('U=\n',U)

L=
 [[ 1  0  0  0]
 [ 5  1  0  0]
 [ 3 -4  1  0]
 [-2  3  2  1]]
U=
 [[ 2  4  5 -3]
 [ 0 -1  2  1]
 [ 0  0  4  2]
 [ 0  0  0  6]]


In [7]:
L =np.array([[1,0,0],[-2,1,0],[4,5,1]])
U =np.array([[2,-1,6],[0,3,9],[0,0,-2]])
b= np.array([18,-3,231])
    
def vorrueck(L,U,b):

    n = L.shape[0]
    y = np.zeros(n)
    y[0] = b[0]
    #Forward Decomposition
    for i in range(1,n):
        y[i]= b[i]-np.dot(L[i,:i],y[:i])

    #Backward Decompoistion
    x = np.zeros(n)
    for i in range(n-1,-1,-1):
        x[i]=(y[i]-np.dot(U[i,i+1:],x[i+1:]))/U[i,i]
    
    return x 
    
vorrueck(L,U,b)

array([1., 2., 3.])